#!/usr/bin/env bash
# deploy-gt.sh [--dry-run <out-dir>] [--live <install-path>]
#
# THE single gated deploy path for gt (DEC-OPS-gt-provenance-contract, Stage 1).
# Refuses to build anything that attest.sh has not verified:
#   - attestation.json must exist (run attest.sh first), and
#   - its treeHash must equal the CURRENT tree hash of HEAD (any commit, amend,
#     or tracked edit after attestation invalidates it), and
#   - the worktree must be clean (tracked files).
# Then builds with the provenance stamp derived FROM THE ATTESTATION (never from
# bare git state), self-checks the stamp, generates the manifest from the stamp,
# and (live mode) atomic-rename installs with a timestamped backup.
#
#   --dry-run <out-dir>   build + stamp + self-check + manifest into out-dir;
#                         no install (container/CI verification mode)
#   --live <install-path> atomic-rename install over the live binary (backup kept)
set -euo pipefail

MODE=""; TARGET=""
case "${1:-}" in
  --dry-run) MODE=dry;  TARGET="${2:?usage: deploy-gt.sh --dry-run <out-dir>}" ;;
  --live)    MODE=live; TARGET="${2:?usage: deploy-gt.sh --live <install-path>}" ;;
  *) echo "usage: deploy-gt.sh --dry-run <out-dir> | --live <install-path>" >&2; exit 2 ;;
esac

HERE="$(cd "$(dirname "$0")" && pwd)"
REPO="$(cd "$HERE/.." && pwd)"
ATT="$HERE/.attest/attestation.json"
GO="${GO:-$HOME/.local/go/bin/go}"; command -v "$GO" >/dev/null 2>&1 || GO="go"

jqget() { sed -n "s/^ *\"$1\": *\"\([^\"]*\)\".*/\1/p" "$ATT" | head -1; }

# ---- Gate: attestation exists, matches this exact tree, tree is clean --------
[ -f "$ATT" ] || { echo "REFUSED: no attestation ($ATT missing). Run deploy/attest.sh first — unverified trees do not get built." >&2; exit 1; }
if [ -n "$(git -C "$REPO" status --porcelain --untracked-files=no)" ]; then
  echo "REFUSED: worktree has uncommitted tracked changes — the attested tree is not what would build." >&2; exit 1
fi
TREE_NOW="$(git -C "$REPO" rev-parse 'HEAD^{tree}')"
TREE_ATT="$(jqget treeHash)"
if [ "$TREE_NOW" != "$TREE_ATT" ]; then
  echo "REFUSED: attestation is for tree ${TREE_ATT:0:12}, but HEAD tree is ${TREE_NOW:0:12} — the tree changed after verification. Re-run attest.sh." >&2; exit 1
fi

VB="$(jqget verifiedBase)"; PSH="$(jqget patchSetSha256)"; AID="$(jqget attestationId)"
COMMIT="$(git -C "$REPO" rev-parse HEAD)"
BRANCH="$(git -C "$REPO" symbolic-ref --short HEAD 2>/dev/null || echo detached)"
VERSION="$(git -C "$REPO" describe --tags --always 2>/dev/null || echo dev)"

# TSV must not have drifted since attestation (it is part of the tree, but belt+braces).
PSH_NOW="$(sha256sum "$HERE/fork-patch-signatures.tsv" | awk '{print $1}')"
[ "$PSH_NOW" = "$PSH" ] || { echo "REFUSED: fork-patch-signatures.tsv hash changed since attestation." >&2; exit 1; }

echo "== building stamped gt (attestation $AID, verifiedBase ${VB:0:9}) =="
M=github.com/steveyegge/gastown/internal/cmd
STAMP="-X $M.VerifiedBase=$VB -X $M.PatchSetHash=$PSH -X $M.AttestationID=$AID \
       -X $M.Version=$VERSION -X $M.Commit=$COMMIT -X $M.Branch=$BRANCH -X $M.Build=deploy"
OUTBIN="$HERE/.attest/stamped-gt"
( cd "$REPO" && CGO_ENABLED=0 "$GO" build -ldflags "$STAMP" -o "$OUTBIN" ./cmd/gt )

echo "== self-check: binary must report the attested provenance =="
PROV="$("$OUTBIN" version --provenance)"
for want in "attested=true" "verifiedBase=$VB" "patchSetHash=$PSH" "attestationId=$AID"; do
  grep -qxF "$want" <<<"$PROV" || { echo "REFUSED: stamped binary does not report '$want'. Got:"; echo "$PROV"; exit 1; }
done
echo "   self-check PASS"

SHA="$(sha256sum "$OUTBIN" | awk '{print $1}')"
TS="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

gen_manifest() { # $1 = path
  cat > "$1" <<EOF
# PINNED-BUILD (GENERATED — do not hand-edit; regenerated by deploy-gt.sh)
# Coherence rule: sha256(deploy/fork-patch-signatures.tsv) == patchSetHash below
#                 == \`gt version --provenance\` of the live binary.
generatedAt: $TS
binarySha256: $SHA
builtFrom: $BRANCH@$COMMIT
verifiedBase: $VB
patchSetHash: $PSH
attestationId: $AID
deployMode: $MODE
EOF
}

if [ "$MODE" = dry ]; then
  mkdir -p "$TARGET"
  cp "$OUTBIN" "$TARGET/gt"
  cp "$ATT" "$TARGET/attestation.json"
  gen_manifest "$TARGET/PINNED-BUILD.generated.md"
  echo "== dry-run complete: $TARGET/{gt,attestation.json,PINNED-BUILD.generated.md} (sha256 ${SHA:0:12}) =="
else
  DEST="$TARGET"; DIR="$(dirname "$DEST")"
  BAK="$DEST.bak-$(date +%Y%m%dT%H%M%S)"
  STAGE="$DIR/.gt-staging-$$"
  cp "$OUTBIN" "$STAGE"                      # stage on the SAME filesystem
  [ -f "$DEST" ] && cp "$DEST" "$BAK"        # timestamped backup of live
  mv -f "$STAGE" "$DEST"                     # atomic rename (never cp onto live: ETXTBSY)
  gen_manifest "$DIR/PINNED-BUILD.generated.md"
  echo "== LIVE deploy complete: $DEST (sha256 ${SHA:0:12}); backup $BAK; manifest $DIR/PINNED-BUILD.generated.md =="
  echo "   next: restart gastown-daemon.service, behavioral-verify, commit the generated manifest to the fork."
fi
